CREATE TABLE EMPRESA (
    CODIGO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    PATRIMONIO INTEGER
);

CREATE TABLE TRABAJADOR (
    NOMBRE VARCHAR2(20),
    FECHA_NACIMIENTO DATE,
    ESTADO_CIVIL VARCHAR2(20),
    EMPRESA INTEGER,
    PRIMARY KEY (NOMBRE),
    FOREIGN KEY (EMPRESA) REFERENCES EMPRESA(CODIGO)
);

INSERT INTO EMPRESA VALUES (1,'ENEL',120);

INSERT INTO EMPRESA VALUES (2,'SAESA',50);

INSERT INTO EMPRESA VALUES (3,'PETROBRAS',100);

INSERT INTO TRABAJADOR  VALUES ('PEDRO','02/08/1990','SOLTERO',1);

INSERT INTO TRABAJADOR  VALUES ('MARIA','02/08/1995','CASADA',1);

INSERT INTO TRABAJADOR  VALUES ('JUAN','02/08/1995','VIUDO',1);

INSERT INTO TRABAJADOR  VALUES ('DIEGO','02/08/1995','SOLTERO',1);

INSERT INTO TRABAJADOR  VALUES ('DOMINGO','02/08/1995','CASADO',2);

SELECT * FROM EMPRESA;

SELECT NOMBRE FROM TRABAJADOR WHERE ESTADO_CIVIL<>'SOLTERO';

SELECT AVG(PATRIMONIO) FROM EMPRESA;

SELECT E.NOMBRE, COUNT(1)
FROM EMPRESA E, TRABAJADOR T
WHERE E.CODIGO=T.EMPRESA
GROUP BY E.NOMBRE
HAVING COUNT(1)>3;

SELECT E.NOMBRE
FROM EMPRESA E
WHERE NOT EXISTS(
	SELECT T.EMPRESA
	FROM TRABAJADOR T
	WHERE E.CODIGO=T.EMPRESA
)

CREATE OR REPLACE VIEW CANT_EMPLEADOS AS (
SELECT E.NOMBRE, E.CODIGO, COUNT(1) AS CANTIDAD
FROM EMPRESA E, TRABAJADOR T
WHERE E.CODIGO=T.EMPRESA
GROUP BY E.NOMBRE, E.CODIGO );

SELECT NOMBRE,CODIGO,CANTIDAD FROM CANT_EMPLEADOS WHERE CANTIDAD = (SELECT MAX(CANTIDAD) FROM CANT_EMPLEADOS);
